version: '3.1'

services:
  mariadb:
    image: mariadb:latest
    container_name: flyingfish_db
    environment:
      MARIADB_AUTO_UPGRADE: '1'
      MARIADB_INITDB_SKIP_TZINFO: '1'
      MYSQL_ROOT_PASSWORD: 'test'
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: 'flyingfish'
    volumes:
      - flyingfishDbData:/var/lib/mysql
    ports:
      - 127.0.0.1:3306:3306
    networks:
      flyingfishNet:
          ipv4_address: 10.103.0.2
    logging:
      driver: "json-file"
      options:
        max-size: "500k"
        max-file: "50"

  influxdb:
    image: influxdb:latest
    container_name: flyingfish_influxdb
    volumes:
      - flyingfishInfluxdbData:/var/lib/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_USERNAME=flyingfish
      - DOCKER_INFLUXDB_INIT_PASSWORD=test
      - DOCKER_INFLUXDB_INIT_ORG=flyingfish
      - DOCKER_INFLUXDB_INIT_BUCKET=flyingfish
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=flyingfish-20220805
    ports:
      - 127.0.0.1:8086:8086
    networks:
      flyingfishNet:
        ipv4_address: 10.103.0.5
    logging:
      driver: "json-file"
      options:
        max-size: "500k"
        max-file: "50"

  flyingfish:
    image: flyingfish:v1.0
    build:
      context: ./
    container_name: flyingfish_service
    volumes:
      - ./config.json:/opt/app/config.json
      - ./nginx:/opt/app/nginx:rw
      - flyingfishLetsencrypt:/etc/letsencrypt:rw
      - flyingfish:/var/lib/flyingfish:rw
    ports:
      - "443:443"
      - "80:80"
      - "5333:53/udp"
      - "5333:53/tcp"
      - "3000:3000"
      - "1900:1900"
      - "9229:9229"
    command:
      - node
      - "--inspect-brk=0.0.0.0:9229"
      - "dist/main.js"
      - "--config=/opt/app/config.json"
    networks:
      flyingfishNet:
        ipv4_address: 10.103.0.3
    logging:
      driver: "json-file"
      options:
        max-size: "500k"
        max-file: "50"
    depends_on:
      - mariadb

  himhip:
    image: flyingfish_himip:v1.0
    build:
      context: ./himhip
    container_name: flyingfish_himhip
    command:
      - node
      - "dist/main.js"
      - "--reciverurl=https://10.103.0.3:3000/himhip/update"
      - "--secure=Dghrk565fn349n5"
    network_mode: host
    cap_add:
      - ALL
    logging:
      driver: "json-file"
      options:
        max-size: "500k"
        max-file: "50"
    depends_on:
      - flyingfish

  sshremote:
    image: flyingfishssh:v1.0
    build:
      context: ./sshserver/
    container_name: flyingfish_ssh
    volumes:
      - ./config.json:/opt/app/config.json
      - ./sshserver/ssh:/opt/app/ssh:rw
    ports:
      - "2222:22"
    networks:
      flyingfishNet:
        ipv4_address: 10.103.0.4
    logging:
      driver: "json-file"
      options:
        max-size: "500k"
        max-file: "50"
    depends_on:
      - mariadb

#  onionhat:
#    image: flyingfishonionhat:v1.0
#    build:
#      context: ./onionhat/
#    container_name: flyingfish_onionhat
#    volumes:
#      - ./config.json:/opt/app/config.json
#    ports:
#      - "9050:9050"
#    networks:
#      flyingfishNet:
#        ipv4_address: 10.103.0.5
#    logging:
#      driver: "json-file"
#      options:
#        max-size: "500k"
#        max-file: "50"
#    depends_on:
#      - mariadb
#      - flyingfish

volumes:
  flyingfishDbData:
    driver: local
  flyingfishInfluxdbData:
      driver: local
  flyingfish:
    driver: local
  flyingfishLetsencrypt:
    driver: local

networks:
  flyingfishNet:
    driver: bridge
    ipam:
      config:
        -  subnet: 10.103.0.0/16