name: Release FlyingFish Docker Images

on:
  release:
    types: [published]
    tags:
      - 'v*.*.*'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout 
        uses: actions/checkout@v2
      
      - name: Login to Docker Hub
        if: github.ref_type == 'tag'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
          
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Docker meta flyingfish
        id: meta_flyingfish
        uses: docker/metadata-action@v4
        with:
          images: ${{ secrets.DOCKER_USERNAME }}/flyingfish
          flavor: latest=true
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}

      - name: Build and push FlyingFish
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile.nginxsrc
          push: ${{ github.ref_type == 'tag' }}
          tags: ${{ steps.meta_flyingfish.outputs.tags }}

      - name: Docker meta flyingfish ssh
        id: meta_flyingfish_ssh
        uses: docker/metadata-action@v4
        with:
          images: ${{ secrets.DOCKER_USERNAME }}/flyingfish_ssh
          flavor: latest=true
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}

      - name: Build and push FlyingFish SSH
        uses: docker/build-push-action@v3
        with:
          context: ./
          file: ./sshserver/Dockerfile
          push: ${{ github.ref_type == 'tag' }}
          tags: ${{ steps.meta_flyingfish.outputs.tags }}

      - name: Docker meta flyingfish himhip
        id: meta_flyingfish_himhip
        uses: docker/metadata-action@v4
        with:
          images: ${{ secrets.DOCKER_USERNAME }}/flyingfish_himip
          flavor: latest=true
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}

      - name: Build and push FlyingFish Himhip
        uses: docker/build-push-action@v3
        with:
          context: ./
          file: ./himhip/Dockerfile
          push: ${{ github.ref_type == 'tag' }}
          tags: ${{ steps.meta_flyingfish_himhip.outputs.tags }}
